name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  standards-entry-check:
    uses: ./.github/workflows/standards-entry-check.yml
